-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE tutor_system.User (
  user_id integer NOT NULL DEFAULT nextval('tutor_system."User_user_id_seq"'::regclass),
  email character varying NOT NULL UNIQUE CHECK (email::text ~ '^[A-Za-z0-9._%+-]+@hcmut\.edu\.vn$'::text),
  hashed_password character varying NOT NULL,
  full_name character varying NOT NULL,
  phone character varying,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['student'::character varying, 'tutor'::character varying, 'coordinator'::character varying, 'admin'::character varying]::text[])),
  avatar_url text,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT User_pkey PRIMARY KEY (user_id)
);
CREATE TABLE tutor_system.attendance (
  attendance_id integer NOT NULL DEFAULT nextval('tutor_system.attendance_attendance_id_seq'::regclass),
  session_id integer NOT NULL,
  student_id integer NOT NULL,
  status character varying DEFAULT 'present'::character varying CHECK (status::text = ANY (ARRAY['present'::character varying, 'late'::character varying, 'absent'::character varying, 'excused'::character varying]::text[])),
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  duration_minutes integer,
  notes text,
  CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id),
  CONSTRAINT attendance_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id)
);
CREATE TABLE tutor_system.coordinator (
  coordinator_id integer NOT NULL DEFAULT nextval('tutor_system.coordinator_coordinator_id_seq'::regclass),
  user_id integer NOT NULL UNIQUE,
  department character varying,
  assigned_subjects jsonb DEFAULT '[]'::jsonb,
  workload integer DEFAULT 0,
  CONSTRAINT coordinator_pkey PRIMARY KEY (coordinator_id),
  CONSTRAINT coordinator_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.coursereport (
  report_id integer NOT NULL DEFAULT nextval('tutor_system.coursereport_report_id_seq'::regclass),
  subject_id integer NOT NULL,
  report_period_start date NOT NULL,
  report_period_end date NOT NULL,
  total_sessions integer DEFAULT 0,
  total_students integer DEFAULT 0,
  total_tutors integer DEFAULT 0,
  avg_session_rating numeric,
  completion_rate numeric,
  metrics jsonb DEFAULT '{}'::jsonb,
  generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT coursereport_pkey PRIMARY KEY (report_id),
  CONSTRAINT coursereport_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id)
);
CREATE TABLE tutor_system.externalresource (
  resource_id integer NOT NULL DEFAULT nextval('tutor_system.externalresource_resource_id_seq'::regclass),
  session_id integer NOT NULL,
  resource_name character varying NOT NULL,
  library_resource_id character varying,
  external_url text,
  source character varying CHECK (source::text = ANY (ARRAY['hcmut_library'::character varying, 'youtube'::character varying, 'other'::character varying]::text[])),
  description text,
  added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT externalresource_pkey PRIMARY KEY (resource_id),
  CONSTRAINT externalresource_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id)
);
CREATE TABLE tutor_system.forum (
  forum_id integer NOT NULL DEFAULT nextval('tutor_system.forum_forum_id_seq'::regclass),
  creator_id integer NOT NULL,
  subject_id integer,
  forum_name character varying NOT NULL,
  description text,
  topic character varying,
  is_public boolean DEFAULT true,
  require_approval boolean DEFAULT false,
  member_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forum_pkey PRIMARY KEY (forum_id),
  CONSTRAINT forum_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES tutor_system.User(user_id),
  CONSTRAINT forum_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id)
);
CREATE TABLE tutor_system.forummember (
  member_id integer NOT NULL DEFAULT nextval('tutor_system.forummember_member_id_seq'::regclass),
  forum_id integer NOT NULL,
  user_id integer NOT NULL,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'moderator'::character varying, 'member'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'pending'::character varying, 'banned'::character varying]::text[])),
  joined_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forummember_pkey PRIMARY KEY (member_id),
  CONSTRAINT forummember_forum_id_fkey FOREIGN KEY (forum_id) REFERENCES tutor_system.forum(forum_id),
  CONSTRAINT forummember_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.forumpost (
  post_id integer NOT NULL DEFAULT nextval('tutor_system.forumpost_post_id_seq'::regclass),
  forum_id integer NOT NULL,
  author_id integer NOT NULL,
  parent_post_id integer,
  title character varying,
  content text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  is_pinned boolean DEFAULT false,
  upvote_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forumpost_pkey PRIMARY KEY (post_id),
  CONSTRAINT forumpost_forum_id_fkey FOREIGN KEY (forum_id) REFERENCES tutor_system.forum(forum_id),
  CONSTRAINT forumpost_author_id_fkey FOREIGN KEY (author_id) REFERENCES tutor_system.User(user_id),
  CONSTRAINT forumpost_parent_post_id_fkey FOREIGN KEY (parent_post_id) REFERENCES tutor_system.forumpost(post_id)
);
CREATE TABLE tutor_system.learning_achievements (
  achievement_id integer NOT NULL DEFAULT nextval('tutor_system.learning_achievements_achievement_id_seq'::regclass),
  student_id integer NOT NULL,
  achievement_type character varying NOT NULL CHECK (achievement_type::text = ANY (ARRAY['first_session'::character varying, 'sessions_10'::character varying, 'sessions_50'::character varying, 'sessions_100'::character varying, 'perfect_attendance'::character varying, 'top_rating'::character varying, 'subject_master'::character varying, 'help_others'::character varying, 'active_member'::character varying, 'study_streak'::character varying]::text[])),
  title character varying NOT NULL,
  description text,
  icon_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  earned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_achievements_pkey PRIMARY KEY (achievement_id),
  CONSTRAINT learning_achievements_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id)
);
CREATE TABLE tutor_system.library_resources_cache (
  cache_id integer NOT NULL DEFAULT nextval('tutor_system.library_resources_cache_cache_id_seq'::regclass),
  library_resource_id character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  authors ARRAY,
  publisher character varying,
  published_year integer,
  isbn character varying,
  resource_type character varying CHECK (resource_type::text = ANY (ARRAY['book'::character varying, 'journal'::character varying, 'thesis'::character varying, 'paper'::character varying, 'video'::character varying, 'other'::character varying]::text[])),
  subject_category character varying,
  description text,
  thumbnail_url text,
  is_available boolean DEFAULT true,
  location character varying,
  call_number character varying,
  cached_at timestamp with time zone DEFAULT now(),
  last_accessed timestamp with time zone DEFAULT now(),
  access_count integer DEFAULT 0,
  CONSTRAINT library_resources_cache_pkey PRIMARY KEY (cache_id)
);
CREATE TABLE tutor_system.matchinglog (
  log_id integer NOT NULL DEFAULT nextval('tutor_system.matchinglog_log_id_seq'::regclass),
  session_id integer NOT NULL,
  student_id integer NOT NULL,
  coordinator_id integer,
  ai_provider character varying,
  ai_model character varying,
  request_data jsonb,
  ai_response jsonb,
  candidates jsonb DEFAULT '[]'::jsonb,
  selected_tutor_id integer,
  match_score numeric CHECK (match_score >= 0::numeric AND match_score <= 100::numeric),
  matching_criteria text,
  processing_time_ms numeric,
  matched_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT matchinglog_pkey PRIMARY KEY (log_id),
  CONSTRAINT matchinglog_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT matchinglog_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id),
  CONSTRAINT matchinglog_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES tutor_system.coordinator(coordinator_id),
  CONSTRAINT matchinglog_selected_tutor_id_fkey FOREIGN KEY (selected_tutor_id) REFERENCES tutor_system.tutor(tutor_id)
);
CREATE TABLE tutor_system.notifications (
  notification_id integer NOT NULL DEFAULT nextval('tutor_system.notifications_notification_id_seq'::regclass),
  user_id integer NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['session_created'::character varying, 'session_updated'::character varying, 'session_cancelled'::character varying, 'registration_approved'::character varying, 'registration_rejected'::character varying, 'feedback_received'::character varying, 'material_uploaded'::character varying, 'forum_reply'::character varying, 'group_invite'::character varying, 'achievement_earned'::character varying, 'system_announcement'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  related_entity_type character varying,
  related_entity_id integer,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (notification_id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.overall_academic_report (
  report_id integer NOT NULL DEFAULT nextval('tutor_system.overall_academic_report_report_id_seq'::regclass),
  report_period_start date NOT NULL,
  report_period_end date NOT NULL,
  total_sessions integer DEFAULT 0,
  completed_sessions integer DEFAULT 0,
  cancelled_sessions integer DEFAULT 0,
  total_students integer DEFAULT 0,
  active_students integer DEFAULT 0,
  total_tutors integer DEFAULT 0,
  active_tutors integer DEFAULT 0,
  verified_tutors integer DEFAULT 0,
  total_subjects integer DEFAULT 0,
  avg_session_rating numeric,
  avg_tutor_rating numeric,
  completion_rate numeric,
  total_forums integer DEFAULT 0,
  total_forum_posts integer DEFAULT 0,
  total_study_groups integer DEFAULT 0,
  subject_breakdown jsonb DEFAULT '{}'::jsonb,
  faculty_breakdown jsonb DEFAULT '{}'::jsonb,
  session_type_breakdown jsonb DEFAULT '{}'::jsonb,
  generated_by integer,
  generated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT overall_academic_report_pkey PRIMARY KEY (report_id),
  CONSTRAINT overall_academic_report_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.progress_tracking (
  progress_id integer NOT NULL DEFAULT nextval('tutor_system.progress_tracking_progress_id_seq'::regclass),
  session_id integer NOT NULL UNIQUE,
  student_id integer NOT NULL,
  subject_id integer NOT NULL,
  topics_covered ARRAY,
  understanding_level integer CHECK (understanding_level >= 1 AND understanding_level <= 5),
  strengths text,
  weaknesses text,
  notes text,
  tutor_feedback text,
  homework_assigned text,
  homework_completed boolean DEFAULT false,
  homework_grade integer CHECK (homework_grade >= 0 AND homework_grade <= 100),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progress_tracking_pkey PRIMARY KEY (progress_id),
  CONSTRAINT progress_tracking_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT progress_tracking_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id),
  CONSTRAINT progress_tracking_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id)
);
CREATE TABLE tutor_system.session (
  session_id integer NOT NULL DEFAULT nextval('tutor_system.session_session_id_seq'::regclass),
  tutor_id integer NOT NULL,
  student_id integer,
  subject_id integer NOT NULL,
  coordinator_id integer,
  title character varying NOT NULL,
  description text,
  scheduled_date date,
  start_time time without time zone,
  end_time time without time zone,
  duration integer DEFAULT 1 CHECK (duration >= 1 AND duration <= 4),
  location_type character varying DEFAULT 'online'::character varying CHECK (location_type::text = ANY (ARRAY['online'::character varying, 'offline'::character varying, 'hybrid'::character varying]::text[])),
  meeting_link text,
  physical_address text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'pending_assignment'::character varying, 'confirmed'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  session_notes text,
  max_students integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT session_pkey PRIMARY KEY (session_id),
  CONSTRAINT session_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES tutor_system.tutor(tutor_id),
  CONSTRAINT session_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id),
  CONSTRAINT session_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id),
  CONSTRAINT session_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES tutor_system.coordinator(coordinator_id)
);
CREATE TABLE tutor_system.session_schedule (
  schedule_id integer NOT NULL DEFAULT nextval('tutor_system.session_schedule_schedule_id_seq'::regclass),
  tutor_id integer NOT NULL,
  subject_id integer NOT NULL,
  title character varying NOT NULL,
  description text,
  is_recurring boolean DEFAULT false,
  recurrence_pattern character varying CHECK (recurrence_pattern::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'biweekly'::character varying, 'monthly'::character varying]::text[])),
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration integer CHECK (duration >= 1 AND duration <= 4),
  location_type character varying DEFAULT 'online'::character varying CHECK (location_type::text = ANY (ARRAY['online'::character varying, 'offline'::character varying, 'hybrid'::character varying]::text[])),
  meeting_link text,
  physical_address text,
  max_students integer DEFAULT 1,
  valid_from date NOT NULL,
  valid_until date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_schedule_pkey PRIMARY KEY (schedule_id),
  CONSTRAINT session_schedule_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES tutor_system.tutor(tutor_id),
  CONSTRAINT session_schedule_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id)
);
CREATE TABLE tutor_system.sessionfeedback (
  feedback_id integer NOT NULL DEFAULT nextval('tutor_system.sessionfeedback_feedback_id_seq'::regclass),
  session_id integer NOT NULL,
  reviewer_id integer NOT NULL,
  reviewer_type character varying NOT NULL CHECK (reviewer_type::text = ANY (ARRAY['student'::character varying, 'tutor'::character varying]::text[])),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  tags jsonb DEFAULT '[]'::jsonb,
  is_public boolean DEFAULT true,
  is_anonymous boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sessionfeedback_pkey PRIMARY KEY (feedback_id),
  CONSTRAINT sessionfeedback_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT sessionfeedback_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.sessionmaterial (
  material_id integer NOT NULL DEFAULT nextval('tutor_system.sessionmaterial_material_id_seq'::regclass),
  session_id integer NOT NULL,
  uploaded_by integer NOT NULL,
  file_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size bigint,
  description text,
  uploaded_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sessionmaterial_pkey PRIMARY KEY (material_id),
  CONSTRAINT sessionmaterial_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT sessionmaterial_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.sessionresponse (
  response_id integer NOT NULL DEFAULT nextval('tutor_system.sessionresponse_response_id_seq'::regclass),
  session_id integer NOT NULL,
  user_id integer NOT NULL,
  responder_type character varying NOT NULL CHECK (responder_type::text = ANY (ARRAY['tutor'::character varying, 'student'::character varying]::text[])),
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['accept'::character varying, 'decline'::character varying, 'request_new_time'::character varying]::text[])),
  reason text,
  proposed_new_time timestamp with time zone,
  is_final boolean DEFAULT false,
  responded_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sessionresponse_pkey PRIMARY KEY (response_id),
  CONSTRAINT sessionresponse_session_id_fkey FOREIGN KEY (session_id) REFERENCES tutor_system.session(session_id),
  CONSTRAINT sessionresponse_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.student (
  student_id integer NOT NULL DEFAULT nextval('tutor_system.student_student_id_seq'::regclass),
  user_id integer NOT NULL UNIQUE,
  student_code character varying NOT NULL UNIQUE,
  faculty character varying,
  major character varying,
  year integer CHECK (year >= 1 AND year <= 5),
  preferences jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT student_pkey PRIMARY KEY (student_id),
  CONSTRAINT student_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.studentregistration (
  registration_id integer NOT NULL DEFAULT nextval('tutor_system.studentregistration_registration_id_seq'::regclass),
  student_id integer NOT NULL,
  subject_id integer NOT NULL,
  learning_goals text,
  urgency character varying DEFAULT 'medium'::character varying CHECK (urgency::text = ANY (ARRAY['high'::character varying, 'medium'::character varying, 'low'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  approved_by integer,
  rejection_reason text,
  registered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  responded_at timestamp with time zone,
  CONSTRAINT studentregistration_pkey PRIMARY KEY (registration_id),
  CONSTRAINT studentregistration_student_id_fkey FOREIGN KEY (student_id) REFERENCES tutor_system.student(student_id),
  CONSTRAINT studentregistration_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id),
  CONSTRAINT studentregistration_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES tutor_system.coordinator(coordinator_id)
);
CREATE TABLE tutor_system.studygroup (
  group_id integer NOT NULL DEFAULT nextval('tutor_system.studygroup_group_id_seq'::regclass),
  creator_id integer NOT NULL,
  subject_id integer,
  group_name character varying NOT NULL,
  description text,
  topic character varying,
  is_public boolean DEFAULT true,
  require_approval boolean DEFAULT false,
  member_count integer DEFAULT 0,
  max_members integer DEFAULT 10,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT studygroup_pkey PRIMARY KEY (group_id),
  CONSTRAINT studygroup_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES tutor_system.User(user_id),
  CONSTRAINT studygroup_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id)
);
CREATE TABLE tutor_system.studygroupmember (
  member_id integer NOT NULL DEFAULT nextval('tutor_system.studygroupmember_member_id_seq'::regclass),
  group_id integer NOT NULL,
  user_id integer NOT NULL,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying, 'member'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'pending'::character varying]::text[])),
  joined_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT studygroupmember_pkey PRIMARY KEY (member_id),
  CONSTRAINT studygroupmember_group_id_fkey FOREIGN KEY (group_id) REFERENCES tutor_system.studygroup(group_id),
  CONSTRAINT studygroupmember_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.studygrouppost (
  post_id integer NOT NULL DEFAULT nextval('tutor_system.studygrouppost_post_id_seq'::regclass),
  group_id integer NOT NULL,
  author_id integer NOT NULL,
  parent_post_id integer,
  content text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT studygrouppost_pkey PRIMARY KEY (post_id),
  CONSTRAINT studygrouppost_parent_post_id_fkey FOREIGN KEY (parent_post_id) REFERENCES tutor_system.studygrouppost(post_id),
  CONSTRAINT studygrouppost_group_id_fkey FOREIGN KEY (group_id) REFERENCES tutor_system.studygroup(group_id),
  CONSTRAINT studygrouppost_author_id_fkey FOREIGN KEY (author_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.subject (
  subject_id integer NOT NULL DEFAULT nextval('tutor_system.subject_subject_id_seq'::regclass),
  subject_code character varying NOT NULL UNIQUE,
  subject_name character varying NOT NULL,
  department character varying,
  credits integer DEFAULT 3,
  description text,
  prerequisites jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT subject_pkey PRIMARY KEY (subject_id)
);
CREATE TABLE tutor_system.tutor (
  tutor_id integer NOT NULL DEFAULT nextval('tutor_system.tutor_tutor_id_seq'::regclass),
  user_id integer NOT NULL UNIQUE,
  staff_code character varying,
  faculty character varying,
  hourly_rate numeric DEFAULT 0,
  bio text,
  rating numeric DEFAULT 0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_sessions integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  teaching_experience jsonb DEFAULT '{}'::jsonb,
  verified_at timestamp with time zone,
  CONSTRAINT tutor_pkey PRIMARY KEY (tutor_id),
  CONSTRAINT tutor_user_id_fkey FOREIGN KEY (user_id) REFERENCES tutor_system.User(user_id)
);
CREATE TABLE tutor_system.tutoractivityreport (
  report_id integer NOT NULL DEFAULT nextval('tutor_system.tutoractivityreport_report_id_seq'::regclass),
  tutor_id integer NOT NULL,
  report_period_start date NOT NULL,
  report_period_end date NOT NULL,
  total_sessions integer DEFAULT 0,
  completed_sessions integer DEFAULT 0,
  avg_rating numeric,
  total_students integer DEFAULT 0,
  total_hours integer DEFAULT 0,
  social_activity_score numeric,
  activity_details jsonb DEFAULT '{}'::jsonb,
  generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tutoractivityreport_pkey PRIMARY KEY (report_id),
  CONSTRAINT tutoractivityreport_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES tutor_system.tutor(tutor_id)
);
CREATE TABLE tutor_system.tutorregistration (
  registration_id integer NOT NULL DEFAULT nextval('tutor_system.tutorregistration_registration_id_seq'::regclass),
  tutor_id integer NOT NULL,
  subject_id integer NOT NULL,
  gpa numeric CHECK (gpa >= 0::numeric AND gpa <= 4.0),
  qualifications text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  approved_by integer,
  rejection_reason text,
  registered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  responded_at timestamp with time zone,
  CONSTRAINT tutorregistration_pkey PRIMARY KEY (registration_id),
  CONSTRAINT tutorregistration_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES tutor_system.tutor(tutor_id),
  CONSTRAINT tutorregistration_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES tutor_system.subject(subject_id),
  CONSTRAINT tutorregistration_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES tutor_system.coordinator(coordinator_id)
);